apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.prefix }}-dev-ops
  namespace: {{ .Values.app.namespace }}
spec:
  type: NodePort
  ports:
  - name: jenkins
    port: 8080
    targetPort: 8080
  - name: nexus
    port: 8081
    targetPort: 8081
  - name: sonarqube
    port: 9000
    targetPort: 9000
  selector:
    app: {{ .Values.app.prefix }}-dev-ops