apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kishan-system-entry
  namespace: kishan
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kishan-system-entry
    spec:
      containers:
        - name: nginx-container
          imagePullPolicy: IfNotPresent
          image: tharanirajan/kishan-system-entry:1.0
          ports:
            - name: http-port
              containerPort: 80