apiVersion: v1
kind: Service
metadata:
  name: kishan-telemetry
  labels:
    app: kishan-telemetry
  namespace: kishan  
spec:
  type: NodePort
  ports:
    - name: vault
      targetPort: 8200
      port: 8200
  selector:
    app: kishan-telemetry