apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: kishan-telemetry
  name: kishan-telemetry
  namespace: kishan
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: kishan-telemetry
    spec:
      containers:
      - name: vault-container
        image: vault
        ports:
        - containerPort: 8200
          name: vaultport
          protocol: TCP
        securityContext:
         capabilities:
           add:
             - IPC_LOCK
        env:
        - name: VAULT_DEV_ROOT_TOKEN_ID
          value: vault-kishan-2019