apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.app.prefix }}-app-mongo-data
  namespace: {{ .Values.app.namepace }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi