apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: {{ .Values.app.prefix }}-logging
  labels:
    app: elasticsearch
spec:
  accessModes: [ "ReadWriteOnce" ]
  resources:
    requests:
      storage: 50Gi
