kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.app.prefix }}-dev-ops-postgres-pvc
  namespace: {{ .Values.app.namespace }}
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi