apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.prefix }}-system-entry
  namespace: {{ .Values.app.namespace }}
spec:
  type: NodePort
  ports:
  - name: nginx-app
    port: 80
    targetPort: 80
  selector:
    app: {{ .Values.app.prefix }}-system-entry