apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.prefix }}-app
  namespace: {{ .Values.app.namespace }}
spec:
  type: NodePort
  ports:
  - name: node-app
    port: 3000
    targetPort: 3000
  selector:
    app: {{ .Values.app.prefix }}-app